name: easy_phone_sign_in
description: "Phone number sign-in package for easy phone sign-in with firebase auth."
version: 0.0.17
homepage: https://github.com/thruthesky/easy_phone_sign_in

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  country_picker: ^2.0.27
  firebase_auth: ^5.6.1
  firebase_core: ^3.15.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

repository: https://github.com/thruthesky/easy_phone_sign_in
issue_tracker: https://github.com/thruthesky/easy_phone_sign_in/issues
topics:
  - phone-sign-in
  - auth
  - sign-in
  - firebase-auth
  - easy-packages
